### ISSUE TITLE
How to boot this OS?

### ISSUE THREAD

**Issue by shanmukhateja** [achilleasa/gopher-os#16]
I like the idea of an OS written in Go but I didn't understand how to get it to boot? Is it GRUB compatible? If so, what should be the `linux` and `initrd` commands for it?

**Comment by cristim** [comment]
As far as I can see in the Makefile, it's simply loaded by Qemu as a CD image in ISO format:
```
run: iso
	qemu-system-$(ARCH) -cdrom $(iso_target)
```

**Comment by tmacychen** [comment]
![20170614215137](https://user-images.githubusercontent.com/3626913/27135699-cdb31bb0-514b-11e7-9a40-882f892b7144.png)

is this a right result？

**Comment by achilleasa** [comment]
Yes, the kernel is still in very early development so it is not doing anything useful yet. The main function just performs some basic initialization and returns which is why you see the above error message.

**Comment by cristim** [comment]
@shanmukhateja, `initrd` is a Linux thing, so it has nothing to do with this.

This OS is so basic that it can't even run anything after it finished loading and just throws that memory dump to see that the memory is actually reachable.
