### ISSUE TITLE
Any simple guide on running this OS

### ISSUE THREAD

**Issue by orklann** [achilleasa/gopher-os#41]
You are doing a nice and fun project.

I am likely to test gopher-os on `Qemu`, is there any simple guide on `building` and `running` this OS on Qemu?

Thank you for your interesting working. :)

**Comment by achilleasa** [comment]
Thanks for your interest in gopher-os. Please keep in mind that the kernel is still in early stages of development so you cannot do anything useful with it yet.

I will be updating the README with more info soon. However, if you want to try it out under qemu you can checkout the code and try running `make run`. For more detailed instructions please take a look at https://github.com/achilleasa/gopher-os/pull/22.

**Comment by darxtrix** [comment]
Hi achilleasa,

Great work indeed. I have been following the issues for a while and I am seeing lots of issues asking for running instructions and all. In the interest of the time, it would be a good idea to add the FAQs to the README so as to prevent duping of such issues and to save some time as well 😄 

Keep the good work going !

Cheers.
