### ISSUE TITLE
Shortcut to self hosting

### ISSUE THREAD

**Issue by Immortalin** [achilleasa/gopher-os#72]
https://github.com/google/gvisor/blob/master/README.md

Once enough is copied over that the go compiler can run successfully then hardest part of OS development is basically over with full bootstrapped self hosting functionality. Of course it's kinda cheating by piggybacking off Linux but who cares 😄

**Comment by dsoprea** [comment]
Cool project.

**Comment by fossfool** [comment]
Following. Very cool idea.
