### ISSUE TITLE
build error: "build cache is required...."

### ISSUE THREAD

**Issue by awsl-dbq** [achilleasa/gopher-os#79]
Please answer these questions before submitting your issue. Thanks!

### Are you trying to build gopher-os inside vagrant or on Linux?

linux

### If building on Linux what is the output of `uname -a`?
Linux viva-la-vida 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What version of Go are you using (`go version`)?
go version go1.14.1 linux/amd64

### What did you do?

If possible, provide a recipe for reproducing the error. 

If reporting a kernel crash please specify if you booted the kernel via 
VirtualBox (`make run-vbox`), qemu (`make run-qemu`) or on real hardware.

### What did you see instead?

If reporting a kernel crash try to attach a screenshot of the kernel output
including any error or panic messages.

```
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
```

**Comment by TotallyGamerJet** [comment]
This doesn't appear to be an issue with the os. Do other go programs compile properly?

**Comment by achilleasa** [comment]
This is an issue when attempting to compile with go 1.14. A workaround is to apply this patch to the offsets tool:

```diff
diff --git a/tools/offsets/offsets.go b/tools/offsets/offsets.go
index 7080e22..ad24778 100644
--- a/tools/offsets/offsets.go
+++ b/tools/offsets/offsets.go
@@ -32,6 +32,7 @@ func genBuildScript(targetOS, targetArch, goBinary, workDir string) ([]byte, err
        // rebuild the runtime packages.
        cmd := exec.Command(goBinary, "build", "-a", "-n")
        cmd.Dir = workDir
+       cmd.Env = append(cmd.Env, fmt.Sprintf("HOME=%s", os.Getenv("HOME")))
        cmd.Env = append(cmd.Env, fmt.Sprintf("GOROOT=%s", os.Getenv("GOROOT")))
        cmd.Env = append(cmd.Env, fmt.Sprintf("GOOS=%s", targetOS))
        cmd.Env = append(cmd.Env, fmt.Sprintf("GOARCH=%s", targetArch))
```

This allows the build to proceed but fails further down with a missing cgo import even though cgo is explicitly disabled. I am still trying to figure out a fix for this.

**Comment by awsl-dbq** [comment]
@achilleasa  thanks and I'll close this issue
